/**
 * M3.1 / M3.2 prep — exportable opportunity brief (Markdown) for Builder seats.
 * Includes score explainability so builders trust the ranking before they buy.
 */

import {
  explainOpportunityScore,
  type OpportunityScores,
} from "./scoring";

export type BriefPainPoint = {
  PainPointId: string;
  Title: string;
  Summary: string;
  Category: string;
  OpportunityScore: number;
  SeverityScore: number;
  FrequencyScore: number;
  WillingnessToPayScore: number;
  TrendScore?: number | null;
  MarketSizeScore?: number | null;
  TrendDirection?: string | null;
};

export type BriefIdea = {
  Name: string;
  Description: string;
  TargetCustomer?: string | null;
  RecommendedFirstFeature?: string | null;
  RevenuePotentialScore?: number | null;
};

function toOpportunityScores(painPoint: BriefPainPoint): OpportunityScores {
  return {
    FrequencyScore: painPoint.FrequencyScore,
    SeverityScore: painPoint.SeverityScore,
    WillingnessToPayScore: painPoint.WillingnessToPayScore,
    TrendScore: Number(painPoint.TrendScore ?? 0),
    MarketSizeScore: Number(painPoint.MarketSizeScore ?? 0),
  };
}

/** Markdown "Why this score" block — pure helper for briefs + unit tests. */
export function formatScoreExplanationMarkdown(
  painPoint: BriefPainPoint
): string {
  const explained = explainOpportunityScore(toOpportunityScores(painPoint));
  const lines: string[] = [
    "## Why this score",
    "",
    `Composite **${explained.total}/100** (${explained.label}). Top driver: **${explained.topDriver.label}** (weight ${(explained.topDriver.weight * 100).toFixed(0)}%, contributes ${explained.topDriver.weighted} pts).`,
    "",
    "| Factor | Raw (0–100) | Weight | Contribution |",
    "| --- | ---: | ---: | ---: |",
  ];
  for (const facet of explained.facets) {
    lines.push(
      `| ${facet.label} | ${facet.raw} | ${(facet.weight * 100).toFixed(0)}% | ${facet.weighted} |`
    );
  }
  lines.push("");
  return lines.join("\n");
}

export function formatOpportunityBriefMarkdown(
  painPoint: BriefPainPoint,
  ideas: BriefIdea[] = []
): string {
  const lines: string[] = [
    `# Opportunity brief: ${painPoint.Title}`,
    "",
    `**Problem ID:** ${painPoint.PainPointId}`,
    `**Category:** ${painPoint.Category}`,
    `**Opportunity score:** ${painPoint.OpportunityScore}`,
    `**Severity / Frequency / Willingness:** ${painPoint.SeverityScore} / ${painPoint.FrequencyScore} / ${painPoint.WillingnessToPayScore}`,
  ];

  if (painPoint.TrendDirection) {
    lines.push(`**Trend:** ${painPoint.TrendDirection}`);
  }

  lines.push("", formatScoreExplanationMarkdown(painPoint).trimEnd(), "");

  lines.push("", "## Summary", "", painPoint.Summary.trim() || "_(no summary)_", "");

  if (ideas.length === 0) {
    lines.push("## Product ideas", "", "_No linked ideas yet._", "");
  } else {
    lines.push("## Product ideas", "");
    for (const [index, idea] of ideas.entries()) {
      lines.push(`### ${index + 1}. ${idea.Name}`);
      lines.push("");
      lines.push(idea.Description.trim() || "_(no description)_");
      if (idea.TargetCustomer) {
        lines.push("");
        lines.push(`- **Target customer:** ${idea.TargetCustomer}`);
      }
      if (idea.RecommendedFirstFeature) {
        lines.push(`- **First feature:** ${idea.RecommendedFirstFeature}`);
      }
      if (
        typeof idea.RevenuePotentialScore === "number" &&
        Number.isFinite(idea.RevenuePotentialScore)
      ) {
        lines.push(`- **Revenue potential:** ${idea.RevenuePotentialScore}`);
      }
      lines.push("");
    }
  }

  lines.push("---", "_Generated by Problems4Us Builder early-access._", "");
  return lines.join("\n");
}
