/**
 * M3.1 prep — exportable opportunity brief (Markdown) for Builder seats.
 */

export type BriefPainPoint = {
  PainPointId: string;
  Title: string;
  Summary: string;
  Category: string;
  OpportunityScore: number;
  SeverityScore: number;
  FrequencyScore: number;
  WillingnessToPayScore: number;
  TrendDirection?: string | null;
};

export type BriefIdea = {
  Name: string;
  Description: string;
  TargetCustomer?: string | null;
  RecommendedFirstFeature?: string | null;
  RevenuePotentialScore?: number | null;
};

export function formatOpportunityBriefMarkdown(
  painPoint: BriefPainPoint,
  ideas: BriefIdea[] = []
): string {
  const lines: string[] = [
    `# Opportunity brief: ${painPoint.Title}`,
    "",
    `**Problem ID:** ${painPoint.PainPointId}`,
    `**Category:** ${painPoint.Category}`,
    `**Opportunity score:** ${painPoint.OpportunityScore}`,
    `**Severity / Frequency / Willingness:** ${painPoint.SeverityScore} / ${painPoint.FrequencyScore} / ${painPoint.WillingnessToPayScore}`,
  ];

  if (painPoint.TrendDirection) {
    lines.push(`**Trend:** ${painPoint.TrendDirection}`);
  }

  lines.push("", "## Summary", "", painPoint.Summary.trim() || "_(no summary)_", "");

  if (ideas.length === 0) {
    lines.push("## Product ideas", "", "_No linked ideas yet._", "");
  } else {
    lines.push("## Product ideas", "");
    for (const [index, idea] of ideas.entries()) {
      lines.push(`### ${index + 1}. ${idea.Name}`);
      lines.push("");
      lines.push(idea.Description.trim() || "_(no description)_");
      if (idea.TargetCustomer) {
        lines.push("");
        lines.push(`- **Target customer:** ${idea.TargetCustomer}`);
      }
      if (idea.RecommendedFirstFeature) {
        lines.push(`- **First feature:** ${idea.RecommendedFirstFeature}`);
      }
      if (
        typeof idea.RevenuePotentialScore === "number" &&
        Number.isFinite(idea.RevenuePotentialScore)
      ) {
        lines.push(`- **Revenue potential:** ${idea.RevenuePotentialScore}`);
      }
      lines.push("");
    }
  }

  lines.push("---", "_Generated by Problems4Us Builder early-access._", "");
  return lines.join("\n");
}
